### ISSUE TITLE
Invalid argument: PartialTensorShape: Incompatible shapes during merge: [212] vs. [275]

### ISSUE THREAD

**Issue by MadhuAtBerkeley** [TensorSpeech/TensorFlowASR#141]
Hi, 
  Thanks for putting together this repo. I could train the conformer (train_subword_conformer) however see the Invalid argument error with test_subword_conformer.py).  The issue is similar to #71 and #79.  I use Tensorflow-gpu version 2.4.1 on Titan RTX.
I am using the default config.yml and shorter version of LibriSpeech (few folders in train-clean-100/dev-clean/test-clean) are used to verify the installation.
   I see the issue on my Mac/CPU version (tensorflow 2.4.1) as well and  the issue goes away on CPU if I use batchsize of 1 instead of 2. However, it makes execution very slow.

Thanks in advance,
Madhu

Reading /tf/TensorFlowASR/LibriSpeech/test-clean/transcripts.tsv ...
2021-02-09 02:30:40.823006: W tensorflow_io/core/kernels/audio_video_mp3_kernels.cc:271] libmp3lame.so.0 or lame functions are not available
2021-02-09 02:30:40.823238: I tensorflow_io/core/kernels/cpu_check.cc:128] Your CPU supports instructions that this TensorFlow IO binary was not compiled to use: AVX2 AVX512F FMA
[Test]:   0%|                                         | 0/31 [00:00<?, ?batch/s]2021-02-09 02:30:41.881288: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-02-09 02:30:41.899042: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3299990000 Hz
2021-02-09 02:31:00.943000: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2021-02-09 02:31:01.995762: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2021-02-09 02:31:02.591532: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2021-02-09 02:31:08.218528: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at list_kernels.h:101 : Invalid argument: PartialTensorShape: Incompatible shapes during merge: [212] vs. [275]
Traceback (most recent call last):
  File "examples/conformer/test_subword_conformer.py", line 97, in <module>
    conformer_tester.run(test_dataset)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_asr/runners/base_runners.py", line 400, in run
    self._test_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_asr/runners/base_runners.py", line 411, in _test_epoch
    decoded = self._test_function(test_iter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 895, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  PartialTensorShape: Incompatible shapes during merge: [212] vs. [275]
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/TensorArrayV2Stack/TensorListStack}}]]
	 [[StatefulPartitionedCall/StatefulPartitionedCall_1/while/body/_1952/while/conformer_beam_search/while/body/_2270/while/conformer_beam_search/while/while/body/_2463/while/conformer_beam_search/while/while/while/body/_2629/while/conformer_beam_search/while/while/while/cond/else/_2799/while/conformer_beam_search/while/while/while/cond/TensorArrayV2Write_1/GreaterEqual/_232]]
  (1) Invalid argument:  PartialTensorShape: Incompatible shapes during merge: [212] vs. [275]
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/TensorArrayV2Stack/TensorListStack}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference__test_function_34931]

Function call stack:
_test_function -> _test_function

2021-02-09 02:31:08.810582: W tensorflow/core/kernels/data/cache_dataset_ops.cc:757] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.

**Comment by usimarit** [comment]
Fixed in the [commit](https://github.com/TensorSpeech/TensorFlowASR/commit/98e13e235cd8d76bfaab279dd1d0585d724e9078).

**Comment by MadhuAtBerkeley** [comment]
Thanks!!
