### ISSUE TITLE
Invalid argument to rsqrt() in train_keras_subwords_conformer

### ISSUE THREAD

**Issue by MadhuAtBerkeley** [TensorSpeech/TensorFlowASR#142]
Hi, 
  I see below error with train_keras_subwords_conformer and it is traced to missing tensor type casting in schedules.py.  Adding step = tf.cast(step, tf.float32) before calling rsqrt() resolved the issue.

Cheers,
Madhu

`def __call__(self, step):
        # lr = (d_model^-0.5) * min(step^-0.5, step*(warm_up^-1.5))
        arg1 = tf.math.rsqrt(step)`
 

        
Traceback (most recent call last):
  File "examples/conformer/train_keras_subword_conformer.py", line 131, in <module>
    steps_per_epoch=train_dataset.total_steps
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 428, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 2336, in on_epoch_end
    self._log_epoch_metrics(epoch, logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 2378, in _log_epoch_metrics
    train_logs = self._collect_learning_rate(train_logs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/callbacks.py", line 2363, in _collect_learning_rate
    logs['learning_rate'] = lr_schedule(self.model.optimizer.iterations)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_asr/optimizers/schedules.py", line 32, in __call__
    arg1 = tf.math.rsqrt(step)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py", line 5006, in rsqrt
    return gen_math_ops.rsqrt(x, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 8017, in rsqrt
    x, name=name, ctx=_ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 8040, in rsqrt_eager_fallback
    ctx=ctx, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of int64 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
; NodeDef: {{node Rsqrt}}; Op<name=Rsqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Rsqrt

**Comment by usimarit** [comment]
Thanks @MadhuAtBerkeley, I updated in the [commit](https://github.com/TensorSpeech/TensorFlowASR/commit/a228193ad789e432f508d8ea3952ca03f2944b12)

**Comment by MadhuAtBerkeley** [comment]
Thanks!!

**Comment by JihyeLimm** [comment]
Thanks!!
