### ISSUE TITLE
[Error while testing the pretrained model]:  PartialTensorShape: Incompatible shapes during merge: [375] vs. [434]

### ISSUE THREAD

**Issue by mukurgupta** [TensorSpeech/TensorFlowASR#143]
Hello,
Thanks a lot for sharing this repo.
I am trying to test the pre-trained confirmer model with test_subword_conformer.py but getting the following error. I have updated the latest commits and using ASRSliceDataset on CPU. Any help would be appreciated.

Thanks.

![issue](https://user-images.githubusercontent.com/38879291/107540475-1729c780-6bec-11eb-8f9d-da9ac8c56cd5.jpg)

**Comment by usimarit** [comment]
Duplicated #141
I'm working on this, meanwhile, please set beam_width to 0 to use only greedy decoding.

**Comment by mukurgupta** [comment]
Hi @usimarit 
Thanks for the response. The beam_width was already 0 when this error occurred.

**Comment by usimarit** [comment]
@mukurgupta Could you give me the full error messages?

**Comment by mjurkus** [comment]
same here, trained `keras_subword_conformer`, beam width is 0

```
Reading /tf_asr/manifests/liepa_test.tsv ...
[Test]:   0%|                                                                                                                                                                                                                     | 0/2982 [00:00<?, ?batch/s]2021-02-10 19:24:44.810174: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-02-10 19:24:45.050328: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-02-10 19:24:46.165095: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at list_kernels.h:101 : Invalid argument: PartialTensorShape: Incompatible shapes during merge: [109] vs. [112]
Traceback (most recent call last):
  File "conformer/test_subword_conformer.py", line 97, in <module>
    conformer_tester.run(test_dataset)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow_asr/runners/base_runners.py", line 401, in run
    self._test_epoch()
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow_asr/runners/base_runners.py", line 412, in _test_epoch
    decoded = self._test_function(test_iter)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  PartialTensorShape: Incompatible shapes during merge: [109] vs. [112]
         [[{{node StatefulPartitionedCall/StatefulPartitionedCall/TensorArrayV2Stack/TensorListStack}}]]
         [[Func/StatefulPartitionedCall/StatefulPartitionedCall/while_1/body/_1315/input/_1428/_66]]
  (1) Invalid argument:  PartialTensorShape: Incompatible shapes during merge: [109] vs. [112]
         [[{{node StatefulPartitionedCall/StatefulPartitionedCall/TensorArrayV2Stack/TensorListStack}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference__test_function_32586]

Function call stack:
_test_function -> _test_function
```

**Comment by mukurgupta** [comment]
@usimarit I have included a full error screenshot in the first comment. That's where it ends😅
Also, I saw that it works in the exact same setting when batch_size is changed to 1.

**Comment by usimarit** [comment]
@mukurgupta @mjurkus Yeah meanwhile please use batch size 1, I'll fix for larger batch size ASAP

**Comment by usimarit** [comment]
@mukurgupta @mjurkus Fixed in the [commit](https://github.com/TensorSpeech/TensorFlowASR/commit/98e13e235cd8d76bfaab279dd1d0585d724e9078)

**Comment by mukurgupta** [comment]
Thanks a lot @usimarit 
Really helps.
