### ISSUE TITLE
New error (when I tried to verify #141)

### ISSUE THREAD

**Issue by MadhuAtBerkeley** [TensorSpeech/TensorFlowASR#150]
Hi,  I see below error with default config.yml file with tensorflow-GPU 4.2.  Please see if this can be fixed.

Thanks Madhu  
   

[Train] |                    | 0/23700 [00:00<?, ?batch/s]2021-02-18 02:18:34.939029: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-02-18 02:18:34.959171: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3299990000 Hz
Traceback (most recent call last):
  File "examples/conformer/train_subword_conformer.py", line 124, in <module>
    conformer_trainer.fit(train_dataset, eval_dataset, train_bs=args.tbs, eval_bs=args.ebs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_asr/runners/base_runners.py", line 311, in fit
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_asr/runners/base_runners.py", line 190, in run
    self._train_epoch()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_asr/runners/base_runners.py", line 213, in _train_epoch
    raise e
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_asr/runners/base_runners.py", line 207, in _train_epoch
    self._train_function(train_iterator)  # Run train step
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 895, in _call
    filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 75, in quick_execute
    raise e
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: conformer/conformer_prediction/strided_slice_1:0

**Comment by MadhuAtBerkeley** [comment]
The train_data_loader is empty and not sure what changed.  I do not see the issue with older revision using same config file

**Comment by usimarit** [comment]
@MadhuAtBerkeley Could you check the train_data to see if it's empty?

**Comment by MadhuAtBerkeley** [comment]
@usimarit, Thanks for looking into it. There is correction -  train_data_loader is not empty and even train_data is not empty.  I see the issue only with tensorflow-gpu 2.4.1.  The CPU version works fine.  I see the error thrown in _train_epoch(below).    Thanks
"
while True:
            try:
                self._train_function(train_iterator)  # Run train step
"

**Comment by MadhuAtBerkeley** [comment]
v0.7.3/v0.7.4 are fine and I see the issue in v0.7.5.  I used the same config file except for the path to subwords file. Please check the delta between v0.7.4 and v0.7.5.

**Comment by usimarit** [comment]
@MadhuAtBerkeley Could you try setting `use_tf: False` in the `train_data_config` and `eval_data_config`?

**Comment by slesinger** [comment]
I get the same error in spite I set use_tf: False in the train_data***set***_config and eval_data***set***_config.

**Comment by MadhuAtBerkeley** [comment]
yes. I see the error even with use_tf: False.  v0.7.4 works for now.

**Comment by usimarit** [comment]
@slesinger @MadhuAtBerkeley Could you guys try again with the new commits on main branch? I've updated the prediction network

**Comment by MadhuAtBerkeley** [comment]
I meant v07.4 works and it is broken in v0.75 and beyond.

**Comment by usimarit** [comment]
I'll try to reproduce the issue, meanwhile, you guys can train models using keras builtin functions (because I'm getting custom training loop deprecated).

**Comment by slesinger** [comment]
I have tried ```python3 train_keras_subword_conformer.py --devices 0 1 --tfrecords --tbs 1```. It ends up with the same error with slightly different stack trace.

**Comment by usimarit** [comment]
@slesinger Could you show me the stack trace? And make sure you use v0.7.7

**Comment by MadhuAtBerkeley** [comment]
I do not see this issue with v0.7.7 anymore.  I moved to python 3.8.8 from 3.6.9 and do not know if it contributed to the resolution.  Thanks

**Comment by slesinger** [comment]
I stayed with default python in container image (3.6.9) and it works for me, too. Thank you.

**Comment by MadhuAtBerkeley** [comment]
Thanks @slesinger and @usimarit
