### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by kijukim1** [TensorSpeech/TensorFlowASR#174]
Hello, I am kinda slow learner of machine learning. I am trying to run testing code (test_subword_conformer.py) with pretrained model (librispeech). I have a problem that this commands don't work for recognizing subwords on my computer. I wonder if I have to modify the environment of my computer. I am working on this with anaconda prompt (anaconda3).  I would be greatly appreciated if you could give me some tips.

(tfasr) C:\Users\username\TensorFlowASR\examples\conformer>python test_subword_conformer.py --config config.yml --subwords /librispeech/subword-conformer/conformer.subwords --saved /librispeech/subword-conformer/latest.h5 --output_name test_results

2021-04-07 22:57:00.833189: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-04-07 22:57:00.837624: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-04-07 22:57:11.726185: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-07 22:57:11.732916: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-04-07 22:57:11.737658: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-04-07 22:57:11.772165: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-VIRQMB1
2021-04-07 22:57:11.777302: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-VIRQMB1
2021-04-07 22:57:18.329696: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-07 22:57:18.341799: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File "test_subword_conformer.py", line 69, in <module>
    raise ValueError("subwords must be set")
ValueError: subwords must be set

**Comment by usimarit** [comment]
@kijukim1 make sure the path to subwords is correct

**Comment by kijukim1** [comment]
I am so grateful for your help! I modified the path and I was able to see "Loading subwords ...".
But I am facing with other problems now... This problem seems to be happened due to difference for number of weights. I wonder how I can make the number of weights same.
Thank you very much again!

(tfasr) C:\Users\username\TensorFlowASR\examples\conformer>python test_subword_conformer.py --config config.yml --subwords libri_conformer.subwords --saved libri_latest.h5 --output_name test_results

2021-04-08 17:44:07.824538: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-04-08 17:44:07.828153: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-04-08 17:44:14.157101: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-08 17:44:14.161319: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-04-08 17:44:14.164352: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-04-08 17:44:14.177809: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-VIRQMB1
2021-04-08 17:44:14.180238: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-VIRQMB1
2021-04-08 17:44:16.940033: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-08 17:44:16.948197: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Loading subwords ...
Traceback (most recent call last):
  File "test_subword_conformer.py", line 88, in <module>
    conformer.load_weights(args.saved)
  File "C:\Users\Kiju Kim\anaconda3\envs\tfasr\lib\site-packages\tensorflow_asr\models\__init__.py", line 59, in load_weights
    super(Model, self).load_weights(filepath, by_name=by_name, skip_mismatch=skip_mismatch, options=options)
  File "C:\Users\Kiju Kim\anaconda3\envs\tfasr\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2234, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "C:\Users\Kiju Kim\anaconda3\envs\tfasr\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 702, in load_weights_from_hdf5_group
    raise ValueError('Layer #' + str(k) + ' (named "' + layer.name +
ValueError: Layer #2 (named "conformer_joint" in the current model) was found to correspond to layer conformer_joint in the save file. However the new layer conformer_joint expects 2 weights, but the saved weights have 5 elements.

**Comment by usimarit** [comment]
@kijukim1 what version of tensorflow_asr do you use? if you're using v0.8.2, can you try using v0.8.1?

**Comment by kijukim1** [comment]
Thank you very much for your response again. I reintalled anaconda3 and tried with v0.8.1. I still see the same problem so I am going to try it with previous version and see if works
I would be appreciated if you could give me any suggestions and tips 🙂

(tfasr) C:\Users\username\TensorFlowASR-0.8.1\examples\conformer>python test_subword_conformer.py --config config.yml --saved latest.h5 --subwords conformer.subwords output_name test_results
2021-04-09 13:54:44.051758: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-04-09 13:54:44.058344: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
usage: Conformer Testing [-h] [--config CONFIG] [--saved SAVED] [--tfrecords] [--mxp] [--sentence_piece]
                         [--device DEVICE] [--cpu] [--subwords SUBWORDS] [--output_name OUTPUT_NAME]
Conformer Testing: error: unrecognized arguments: output_name test_results

(tfasr) C:\Users\username\TensorFlowASR-0.8.1\examples\conformer>python test_subword_conformer.py --config config.yml --saved latest.h5 --subwords conformer.subwords --output_name test_results
2021-04-09 13:55:43.606480: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-04-09 13:55:43.612904: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-04-09 13:55:48.163787: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-09 13:55:48.174002: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-04-09 13:55:48.182938: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-04-09 13:55:48.204458: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-E6GDE4B
2021-04-09 13:55:48.213493: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-E6GDE4B
2021-04-09 13:55:53.817338: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-09 13:55:53.828797: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Loading subwords ...
Traceback (most recent call last):
  File "test_subword_conformer.py", line 88, in <module>
    conformer.load_weights(args.saved)
  File "C:\Users\username\anaconda3\envs\tfasr\lib\site-packages\tensorflow_asr\models\__init__.py", line 59, in load_weights
    super(Model, self).load_weights(filepath, by_name=by_name, skip_mismatch=skip_mismatch, options=options)
  File "C:\Users\username\anaconda3\envs\tfasr\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2234, in load_weights
    hdf5_format.load_weights_from_hdf5_group(f, self.layers)
  File "C:\Users\username\anaconda3\envs\tfasr\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 702, in load_weights_from_hdf5_group
    raise ValueError('Layer #' + str(k) + ' (named "' + layer.name +
ValueError: Layer #2 (named "conformer_joint" in the current model) was found to correspond to layer conformer_joint in the save file. However the new layer conformer_joint expects 2 weights, but the saved weights have 5 elements.

**Comment by usimarit** [comment]
@kijukim1 Did you use the right config from google drive? I just tested on my machine and it loads the weight fine.

**Comment by kijukim1** [comment]
@usimarit I really appreciate your tip again! I don't see any weight-related errors now after I replace with the config file as you mentioned. Now I can see information about number of parameters here. 

I am facing with just a couple of errors in this moment.

In config.yml file, I put a tsv file which is created from create_librispeech_trans.py (TensorFlowASR/scripts/create_librispeech_trans.py)and 367-130732.trans.txt from downloaded LibriSpeech dataset (LibriSpeech\test-other\367\130732\367-130732.trans.txt)

Thank you so much again and I will also post config.yml file to resolve problem faster.

(tfasr) C:\Users\username\TensorFlowASR\examples\conformer>python test_subword_conformer.py --config config.yml --subwords conformer.subwords --saved latest.h5 --output_name test_results
2021-04-10 15:55:53.911712: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-04-10 15:55:53.914923: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Namespace(config='config.yml', cpu=False, device=0, mxp=False, output_name='test_results', saved='libri_latest.h5', sentence_piece=False, subwords='libri_conformer.subwords', tfrecords=False)
2021-04-10 15:56:00.142947: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-10 15:56:00.147136: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-04-10 15:56:00.148925: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-04-10 15:56:00.161874: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-VIRQMB1
2021-04-10 15:56:00.164397: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-VIRQMB1
2021-04-10 15:56:03.227766: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-10 15:56:03.235547: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Loading subwords ...
Model: "conformer_encoder"
________________________________________________________________________________________________________________________
Layer (type)                                          Output Shape                                    Param #           
========================================================================================================================
conformer_encoder_subsampling (Conv2dSubsampling)     multiple                                        188208            
________________________________________________________________________________________________________________________
conformer_encoder_pe (PositionalEncodingConcat)       multiple                                        0                 
________________________________________________________________________________________________________________________
conformer_encoder_linear (Dense)                      multiple                                        414864            
________________________________________________________________________________________________________________________
conformer_encoder_dropout (Dropout)                   multiple                                        0                 
________________________________________________________________________________________________________________________
conformer_encoder_block_0 (ConformerBlock)            multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_1 (ConformerBlock)            multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_2 (ConformerBlock)            multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_3 (ConformerBlock)            multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_4 (ConformerBlock)            multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_5 (ConformerBlock)            multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_6 (ConformerBlock)            multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_7 (ConformerBlock)            multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_8 (ConformerBlock)            multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_9 (ConformerBlock)            multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_10 (ConformerBlock)           multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_11 (ConformerBlock)           multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_12 (ConformerBlock)           multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_13 (ConformerBlock)           multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_14 (ConformerBlock)           multiple                                        506736            
________________________________________________________________________________________________________________________
conformer_encoder_block_15 (ConformerBlock)           multiple                                        506736            
========================================================================================================================
Total params: 8,710,848
Trainable params: 8,706,240
Non-trainable params: 4,608
________________________________________________________________________________________________________________________
Model: "conformer_prediction"
________________________________________________________________________________________________________________________
Layer (type)                                          Output Shape                                    Param #           
========================================================================================================================
conformer_prediction_embedding (Embedding)            multiple                                        329920            
________________________________________________________________________________________________________________________
conformer_prediction_dropout (Dropout)                multiple                                        0                 
________________________________________________________________________________________________________________________
conformer_prediction_ln_0 (LayerNormalization)        multiple                                        640               
________________________________________________________________________________________________________________________
conformer_prediction_lstm_0 (LSTM)                    multiple                                        820480            
========================================================================================================================
Total params: 1,151,040
Trainable params: 1,151,040
Non-trainable params: 0
________________________________________________________________________________________________________________________
Model: "conformer_joint"
________________________________________________________________________________________________________________________
Layer (type)                                          Output Shape                                    Param #           
========================================================================================================================
conformer_joint_enc (Dense)                           multiple                                        46400             
________________________________________________________________________________________________________________________
conformer_joint_pred (Dense)                          multiple                                        102400            
________________________________________________________________________________________________________________________
conformer_joint_vocab (Dense)                         multiple                                        330951            
========================================================================================================================
Total params: 479,751
Trainable params: 479,751
Non-trainable params: 0
________________________________________________________________________________________________________________________
Model: "conformer"
________________________________________________________________________________________________________________________
Layer (type)                                          Output Shape                                    Param #           
========================================================================================================================
conformer_encoder (ConformerEncoder)                  multiple                                        8710848           
________________________________________________________________________________________________________________________
conformer_prediction (TransducerPrediction)           multiple                                        1151040           
________________________________________________________________________________________________________________________
conformer_joint (TransducerJoint)                     multiple                                        479751            
========================================================================================================================
Total params: 10,341,639
Trainable params: 10,337,031
Non-trainable params: 4,608
________________________________________________________________________________________________________________________
[Test]: 0batch [00:00, ?batch/s]Traceback (most recent call last):
  File "test_subword_conformer.py", line 98, in <module>
    conformer_tester.run(test_dataset)
  File "C:\Users\username\anaconda3\envs\tfasr\lib\site-packages\tensorflow_asr\runners\base_runners.py", line 400, in run
    self._test_epoch()
  File "C:\Users\username\anaconda3\envs\tfasr\lib\site-packages\tensorflow_asr\runners\base_runners.py", line 408, in _test_epoch
    test_iter = iter(self.test_data_loader)
TypeError: 'NoneType' object is not iterable
[Test]: 0batch [00:00, ?batch/s]

**Comment by kijukim1** [comment]
Here is the config.yml that I used. 
I would be appreciated again if you could give me tips.

speech_config:
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  feature_type: log_mel_spectrogram
  num_feature_bins: 80
  preemphasis: 0.97
  normalize_signal: True
  normalize_feature: True
  normalize_per_feature: False

decoder_config:
  vocabulary: null
  target_vocab_size: 1024
  max_subword_length: 4
  blank_at_zero: True
  beam_width: 0
  norm_score: True

model_config:
  name: conformer
  encoder_subsampling:
    type: conv2d
    kernel_size: 3
    strides: 2
    filters: 144
  encoder_positional_encoding: sinusoid_concat
  encoder_dmodel: 144
  encoder_num_blocks: 16
  encoder_head_size: 36
  encoder_num_heads: 4
  encoder_mha_type: relmha
  encoder_kernel_size: 32
  encoder_fc_factor: 0.5
  encoder_dropout: 0.1
  prediction_embed_dim: 320
  prediction_embed_dropout: 0.0
  prediction_num_rnns: 1
  prediction_rnn_units: 320
  prediction_rnn_type: lstm
  prediction_rnn_implementation: 1
  prediction_layer_norm: True
  joint_dim: 320

learning_config:
  augmentations:
    after:
      time_masking:
        num_masks: 10
        mask_factor: 100
        p_upperbound: 0.05
      freq_masking:
        num_masks: 1
        mask_factor: 27

  dataset_config:
    train_paths: null
    eval_paths: null
    test_paths:
      - C:/Users/username/TensorFlowASR/examples/conformer/subword-conformer/test-other/output_libri367.tsv
    tfrecords_dir: null

  optimizer_config:
    warmup_steps: 40000
    beta1: 0.9
    beta2: 0.98
    epsilon: 1e-9

  gradpolicy:
    train_size: 100
    smooth_win_size: 2
    hist_size: 50
    policy_name: "simple"

  running_config:
    batch_size: 4
    accumulation_steps: 4
    num_epochs: 20
    outdir: C:/Users/username/TensorFlowASR/examples/conformer/subword-conformer
    log_interval_steps: 500
    save_interval_steps: 500
    eval_interval_steps: 2000

**Comment by usimarit** [comment]
@kijukim1 I uploaded the new config format on google drive, please update it.

**Comment by kijukim1** [comment]
@usimarit Thank you very much again! Since I see the statement "Reading C:\Users\username\TensorFlowASR\examples\conformer\test-other\LibriSpeech\test-other\367\130732\367-130732-0001.wav ..." at the bottom of information about parameters, I don't think config.yml file has problems anymore.

I still see some errors in the bottom so I also checked tsv file that I used. I created tsv file (output_libri_367_103702.tsv) with create_librispeech_trans.py file and LibriSpeech dataset (LibriSpeech\test-other\367\130732\367-130732.trans.txt). I opened it with excel program and I saw I only see PATH, DURATION and TRANSCRIPT without any data from the dataset. I assume that the error still comes out due to such reason.
I wonder if I use wrong file to create tsv file.

Again I really appreciate your tips!

![image](https://user-images.githubusercontent.com/82136772/114334103-b725a380-9afe-11eb-9e76-2cb7a1b8c6b5.png)
![image](https://user-images.githubusercontent.com/82136772/114334294-23080c00-9aff-11eb-810b-2a637ff6733c.png)

**Comment by usimarit** [comment]
@kijukim1 Assume your test-other is `LibriSpeech\test-other` then pass the option `--dir LibriSpeech\test-other` when running the 
`create_librispeech_trans.py` script

**Comment by kijukim1** [comment]
Great! I will check this out.
I did copy & paste contents below path, duration and transcript. It works pretty well.

I really appreciate your help for whole procedure.

**Comment by aidansmyth95** [comment]
This was a very useful thread, was stuck on loading pretrained conformer too. Thanks to everyone involved.
