### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by o74589055** [TensorSpeech/TensorFlowASR#222]
Hi! I am a novice
I get an error when I run conformer/train.py
```bash
$ python train.py --subwords --config config.yml --pretrained conformer-encoder.h5 
```
## Error
```bash
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    blank=text_featurizer.blank
  File "/app/examples/conformer/tensorflow_asr/models/transducer/transducer.py", line 354, in compile
    super().compile(loss=loss, optimizer=optimizer, run_eagerly=run_eagerly, **kwargs)
  File "/app/examples/conformer/tensorflow_asr/models/base_model.py", line 88, in compile
    self.add_metric(loss_metric)
  File "/app/examples/conformer/tensorflow_asr/models/base_model.py", line 70, in add_metric
    self._metrics[metric.name] = metric
TypeError: list indices must be integers or slices, not str
```

**Comment by w81192** [comment]
the author commit base_model.py a few days ago，he modified the code about function self.add_metric in base_model.py，that would make a error when you are running the train.py. So just use the history version，that would be ok

**Comment by o74589055** [comment]
I think it’s a TensorFlowASR version issue. I didn’t switch branches. I executed docker-compose and then pip3 install -U "TensorFlowASR[tf2.x-gpu]"

**Comment by usimarit** [comment]
Can you guys try the newest one on brandh main to see if the issue still exists?
