### ISSUE TITLE
training with LibriSpeech problem

### ISSUE THREAD

**Issue by wwyl2000** [TensorSpeech/TensorFlowASR#261]
Hi,
I tried to train conformer CTC subword models with LibriSpeech and got some problems. The training stopped after one epoch, and i did not see saved models. Following is the information i got after ending the 1st epoch.

-----------
14269/14269 [==============================] - ETA: 0s - loss: 382.10812022-07-24 22:14:38.276447: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:766] AUTO sharding policy will apply DATA sharding policy as it failed to apply FILE sharding policy because of the following reason: Found an unshardable source dataset: name: "TensorSliceDataset/_1"
op: "TensorSliceDataset"
input: "Placeholder/_0"
attr {
  key: "Toutput_types"
  value {
    list {
      type: DT_STRING
    }
  }
}
attr {
  key: "_cardinality"
  value {
    i: 2703
  }
}
attr {
  key: "is_files"
  value {
    b: false
  }
}
attr {
  key: "metadata"
  value {
    s: "\n\024TensorSliceDataset:8"
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: 3
        }
      }
    }
  }
}

Traceback (most recent call last):
  File "./train.py", line 131, in <module>
    main()
  File "./train.py", line 125, in main
    validation_steps=eval_dataset.total_steps if eval_data_loader else None,
  File "/home/myenv/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
  File "/home/myenv/lib/python3.7/site-packages/keras/engine/training.py", line 1263, in fit
    _use_cached_eval_dataset=True)
  File "/home/myenv/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
  File "/home/myenv/lib/python3.7/site-packages/keras/engine/training.py", line 1537, in evaluate
    tmp_logs = self.test_function(iterator)
  File "/home/myenv/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/home/myenv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 910, in __call__
    result = self._call(*args, **kwds)
  File "/home/myenv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 949, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/myenv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3131, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/myenv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1960, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/myenv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 603, in call
    ctx=ctx)
  File "/home/myenv/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    inputs, attrs, num_outputs)
KeyboardInterrupt
Terminated

------
Here are some questions I hope to get help:
1. Why the training did not continue after one epoch?
2. Why no models were saved?
3. The batch_size  was set to 2, which i feel is too small. I tried to set to bigger value, say 4, but I got problem.

Thanks for your help!

WWY

**Comment by wwyl2000** [comment]
Solved!
