### ISSUE TITLE
Should I use eager mode?

### ISSUE THREAD

**Issue by magdacisowska** [TensorSpeech/TensorFlowASR#51]
I have a question about whether should I use the eager or graph mode while launching trainining scripts. The thing is that in my tf 2.4 I have it disabled by default, which results in errors in all calls to some_tensor.numpy(). However, when I enable the eager mode manually at the begining of the script, I end up getting even more errors, at even earlier stages of the training.
So far I was able to run the training script with eager mode disabled,  while commenting out all calls to .numpy()

**Comment by usimarit** [comment]
@magdacisowska Can you show me the errors when you enable eager mode manually? As I see in the docs, tf2 enable eager mode by default and I haven't met any problems.
My trainer only uses .numpy() when displaying the current epoch on the progress bar, if you don't need the epoch information on the progress bar, then using only graph mode (by commenting out that line) is not a problem.

**Comment by magdacisowska** [comment]
ok, so I enable (in train_streaming_transducer.py) the eager mode. So I get:

`
Traceback (most recent call last):
  File "examples/streaming_transducer/train_streaming_transducer.py", line 115, in <module>
    streaming_transducer._build(speech_featurizer.shape)
  File "/home/mcisowska/.local/lib/python3.6/site-packages/TensorFlowASR-0.3.0-py3.6.egg/tensorflow_asr/models/transducer.py", line 234, in _build
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/mcisowska/.local/lib/python3.6/site-packages/TensorFlowASR-0.3.0-py3.6.egg/tensorflow_asr/models/transducer.py", line 268, in call
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/mcisowska/.local/lib/python3.6/site-packages/TensorFlowASR-0.3.0-py3.6.egg/tensorflow_asr/models/streaming_transducer.py", line 156, in call
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/mcisowska/.local/lib/python3.6/site-packages/TensorFlowASR-0.3.0-py3.6.egg/tensorflow_asr/models/streaming_transducer.py", line 73, in call
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/recurrent.py", line 660, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/recurrent.py", line 2783, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/recurrent.py", line 804, in call
    zero_output_for_mask=self.zero_output_for_mask)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py", line 4335, in rnn
    for i, inp in enumerate(flatted_inputs))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py", line 4335, in <genexpr>
    for i, inp in enumerate(flatted_inputs))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 1082, in __init__
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 718, in __init__
    self._tensor_array = [None for _ in range(size)]
TypeError: 'Tensor' object cannot be interpreted as an integer
`

**Comment by magdacisowska** [comment]
Ok it turned out that the eager mode should be also turned on in utils module, as it is imported before the tensorflow
