### ISSUE TITLE
InvalidArgumentError during test of conformer

### ISSUE THREAD

**Issue by gandroz** [TensorSpeech/TensorFlowASR#72]
I encountered an `InvalidArgumentError` error during testing phase. I haven't had any issue during training, only when trying to test the resulting model.

```
Traceback (most recent call last):
  File "examples/conformer/test_conformer.py", line 97, in <module>
    conformer_tester.run(test_dataset)
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/TensorFlowASR-0.4.0-py3.8.egg/tensorflow_asr/runners/base_runners.py", line 405, in run
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/TensorFlowASR-0.4.0-py3.8.egg/tensorflow_asr/runners/base_runners.py", line 416, in _test_epoch
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
         [[{{node StatefulPartitionedCall/StatefulPartitionedCall_1/map/while/body/_3023/map/while/conformer_beam_search/TensorArrayV2Write_2/TensorListSetItem/_184}}]]
  (1) Invalid argument:  2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
         [[{{node StatefulPartitionedCall/StatefulPartitionedCall_1/map/while/body/_3023/map/while/conformer_beam_search/TensorArrayV2Write_2/TensorListSetItem/_184}}]]
         [[StatefulPartitionedCall/StatefulPartitionedCall_2/map/while/body/_3651/map/while/conformer_beam_search/TensorArrayV2Write_1/TensorListSetItem/_188]]
0 successful operations.
0 derived errors ignored. [Op:__inference__test_function_50368]

Function call stack:
_test_function -> _test_function
```

That's the arguments passed to the TF function:

```
OP name __inference__test_function_50368
Attrs ('executor_type', '', 'config_proto', b'\n\x07\n\x03CPU\x10\x01\n\x07\n\x03GPU\x10\x012\x05*\x010J\x008\x01R\x05R\x03\xb8\x01\x02\x82\x01\x00')
```

**Comment by usimarit** [comment]
duplicated #71
