### ISSUE TITLE
streaming tflite conformer giving pretty bad results

### ISSUE THREAD

**Issue by ahsanmemon** [TensorSpeech/TensorFlowASR#76]
Hi, 
I tested the demonstration/streaming_tflite_conformer.py file as following
`python examples/demonstration/streaming_tflite_conformer.py "/home/ahsanmemon/Desktop/LibriSpeech/test-clean/61/70968/61-70968-0000.flac" --tflite "models/conformer-tflite/subsampling-conformer.latest.tflite"`

and
`python examples/demonstration/streaming_tflite_conformer.py "/home/ahsanmemon/Desktop/LibriSpeech/test-clean/61/70968/61-70968-0000.flac" --tflite "models/conformer-tflite/subword-conformer.latest.tflite"`

However, both the times, I got really funny results.
Ground Truth was: **he began a confused complaint against the wizard who had vanished behind the curtain.**
Output was as following
![image](https://user-images.githubusercontent.com/28605862/101992653-cb839c00-3cd6-11eb-9613-f6584c39cef5.png)

and 

![image](https://user-images.githubusercontent.com/28605862/101992689-dfc79900-3cd6-11eb-95f7-1739df81cf8e.png)

for **subword** and **subsampling** tflite pretrained models that you uploaded on your drive.

Is there something that I am missing in particular?

**Comment by ahsanmemon** [comment]
Just FYI,
I also checked outputs of the demonstration/tflite_conformer.py and they are giving pretty decent results tbh.

Here are the results
`python examples/demonstration/tflite_conformer.py "/home/ahsanmemon/Desktop/LibriSpeech/test-clean/61/70968/61-70968-0000.flac" --tflite "models/conformer-tflite/subword-conformer.latest.tflite"`

predicted: **he began to confuse complaint against the wizard who had vanished behind the curtain on the left**


`python examples/demonstration/tflite_conformer.py "/home/ahsanmemon/Desktop/LibriSpeech/test-clean/61/70968/61-70968-0000.flac" --tflite "models/conformer-tflite/subsampling-conformer.latest.tflite"`

predicted: **he began a confused claim against twizard who vanished hind turtin on the eff**

**Comment by usimarit** [comment]
Conformer is not for streaming, I wrote that demonstration to prove it. Only models that have unidirectional rnn in the encoder are good for streaming tasks.

**Comment by ahsanmemon** [comment]
Great. Thanks for the info. 
Is there a streaming demo for the streaming transducer (examples/streaming_transducer) that we can probably use?

**Comment by usimarit** [comment]
You can create one using the conformer demo. Just replace conformer with streaming transducer.

**Comment by ahsanmemon** [comment]
great. thanks.

**Comment by ahsanmemon** [comment]
I tried using tflite version of streaming transducer but it didn't work. Is it possible for you to upload a demonstration of it?

**Comment by ahsanmemon** [comment]
I tried using tflite version of streaming transducer but it didn't work. Is it possible for you to upload a demonstration of it?

**Comment by JeongWoonPark** [comment]
Hi, @ahsanmemon 
I try to run `python streaming_tflite_conformer.py` with `subsampling-conformer.latest.tflite`
But I got the below error
```
RuntimeError: Internal psf_fseek() failed.
INFO: Created TensorFlow Lite delegate for select TF ops.
2020-12-24 14:50:09.152221: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-12-24 14:50:09.163397: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2194910000 Hz
2020-12-24 14:50:09.167566: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560961135d90 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-12-24 14:50:09.167609: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
INFO: TfLiteFlexDelegate delegate: 211 nodes delegated out of 2665 nodes with 130 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 26 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 1 nodes delegated out of 40 nodes with 1 partitions.

Process Process-2:
Traceback (most recent call last):
  File "/home/pjw1210/anaconda3/envs/tfasrcpu/lib/python3.7/multiprocessing/managers.py", line 811, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pjw1210/anaconda3/envs/tfasrcpu/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/pjw1210/anaconda3/envs/tfasrcpu/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "examples/demonstration/streaming_tflite_conformer.py", line 113, in recognizer
    data = Q.get()
  File "<string>", line 2, in get
  File "/home/pjw1210/anaconda3/envs/tfasrcpu/lib/python3.7/multiprocessing/managers.py", line 815, in _callmethod
    self._connect()
  File "/home/pjw1210/anaconda3/envs/tfasrcpu/lib/python3.7/multiprocessing/managers.py", line 802, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/home/pjw1210/anaconda3/envs/tfasrcpu/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/home/pjw1210/anaconda3/envs/tfasrcpu/lib/python3.7/multiprocessing/connection.py", line 620, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

Did you encounter this? if so, How solved?

Thanks

**Comment by imoldfella** [comment]
In case you didn't see it, the authors of this paper had success combining conformer with transducer: https://arxiv.org/pdf/2010.11395.pdf

**Comment by usimarit** [comment]
@imoldfella Nice one, I didn't notice, I'll support this paper soon :smile:
