### ISSUE TITLE
IndexError during testing of subword_conformer

### ISSUE THREAD

**Issue by gandroz** [TensorSpeech/TensorFlowASR#79]
I got this error in TF

```
[Test]:   0%|                            | 0/2620 [00:00<?, ?batch/s]
2020-12-14 10:58:11.370953: W tensorflow/core/framework/op_kernel.cc:1755] Unknown: IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):

  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/tmp/tmpe_qwazkp.py", line 34, in decode
    ag__.if_stmt((ag__.ld(x)[0] == ag__.ld(self).blank), if_body, else_body, get_state, set_state, ('x',), 1)

IndexError: index 0 is out of bounds for axis 0 with size 0


Traceback (most recent call last):
  File "examples/conformer/test_subword_conformer.py", line 105, in <module>
    conformer_tester.run(test_dataset)
  File "/home/guillaume/src/desjardins/TensorFlowASR/tensorflow_asr/runners/base_runners.py", line 405, in run
    self._test_epoch()
  File "/home/guillaume/src/desjardins/TensorFlowASR/tensorflow_asr/runners/base_runners.py", line 416, in _test_epoch
    decoded = self._test_function(test_iter)
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 846, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):

  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/tmp/tmpe_qwazkp.py", line 34, in decode
    ag__.if_stmt((ag__.ld(x)[0] == ag__.ld(self).blank), if_body, else_body, get_state, set_state, ('x',), 1)

IndexError: index 0 is out of bounds for axis 0 with size 0


         [[{{node StatefulPartitionedCall/StatefulPartitionedCall_1/map/while/body/_3064/map/while/map_1/while/body/_9901/map/while/map_1/while/PyFunc}}]]
         [[StatefulPartitionedCall/StatefulPartitionedCall_2/map/while/body/_3687/map/while/conformer_beam_search/while/body/_9938/map/while/conformer_beam_search/while/while/body/_10485/map/while/conformer_beam_search/while/while/conformer_decoder/conformer_prediction_embedding/ExpandDims/_3676]]
  (1) Unknown:  IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):

  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 244, in __call__
    ret = func(*args)

  File "/home/guillaume/miniconda3/envs/stt/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/tmp/tmpe_qwazkp.py", line 34, in decode
    ag__.if_stmt((ag__.ld(x)[0] == ag__.ld(self).blank), if_body, else_body, get_state, set_state, ('x',), 1)

IndexError: index 0 is out of bounds for axis 0 with size 0


         [[{{node StatefulPartitionedCall/StatefulPartitionedCall_1/map/while/body/_3064/map/while/map_1/while/body/_9901/map/while/map_1/while/PyFunc}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference__test_function_50525]

Function call stack:
_test_function -> _test_function
```

Any idea why ?

**Comment by gandroz** [comment]
Thanks for the update, it fixed the problem, can you elaborate on the fix please ?
Although, I still got the `Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string` error as in #71 but the fix I suggested solves it (running the greedy and beam search `tf.map_fn` on CPU explicitly as wrapping only the beam search is not enough)

**Comment by usimarit** [comment]
Actually I didn't fix anything, I just cleaned the code a little bit and told you to try again :laughing: You can checkout the [commit](https://github.com/TensorSpeech/TensorFlowASR/commit/83d1b7058da8c6cfe603cbed80ff2d65ee0eaf3f) to see what I did.

**Comment by gandroz** [comment]
well, you surely fix something more than just cleaning the code as now it works ;)

**Comment by usimarit** [comment]
At line 523, the `tf.expand_dims(y_hat_score_index[0], axis=-1)` and `y_hat_score_index` are the same since `y_hat_score_index` is from `tf.top_k(k=1)` :laughing:
There're some mysterious things that happen some time :)
Anyway, what is this file in your error log?
```bash
File "/tmp/tmpe_qwazkp.py", line 34, in decode
    ag__.if_stmt((ag__.ld(x)[0] == ag__.ld(self).blank), if_body, else_body, get_state, set_state, ('x',), 1)

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by gandroz** [comment]
> Anyway, what is this file in your error log?

I dont have any idea ! it looks like some temporary file generated by tf ?

**Comment by usimarit** [comment]
@gandroz I guess so, I'll close this issue here since it's resolved.
