### ISSUE TITLE
ValueError when running test_subword_conformer.py

### ISSUE THREAD

**Issue by mjurkus** [TensorSpeech/TensorFlowASR#80]
**TensorFlowASR version**: 0.4.3

I used `train_ga_subword_conformer.py` to train my model.

Used same `config.yml` to run `test_subword_conformer.py` with 

```
python conformer/test_subword_conformer.py --saved models/latest.h5 --subwords vocabularies/lithuanian.characters.subwords
```
and I get 

```python
ValueError: in user code:

    /opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow_asr/runners/base_runners.py:431 _test_function  *
        return self._test_step(batch)
    /opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow_asr/runners/base_runners.py:443 _test_step  *
        file_paths, signals, labels = batch

    ValueError: too many values to unpack (expected 3)
```

I checked what's happening there ant it seems, that it receives such batch:
```
<tf.Tensor 'IteratorGetNext:0' shape=(1,) dtype=string>, <tf.Tensor 'IteratorGetNext:1' shape=(1, None, 80, 1) dtype=float32>, <tf.Tensor 'IteratorGetNext:2' shape=(1,) dtype=int32>, <tf.Tensor 'IteratorGetNext:3' shape=(1, None) dtype=int32>, <tf.Tensor 'IteratorGetNext:4' shape=
(1,) dtype=int32>, <tf.Tensor 'IteratorGetNext:5' shape=(1, None) dtype=int32>)
```

**Comment by gandroz** [comment]
@mjurkus Do you know the difference between `train_ga_subword_conformer` and `train_subword_conformer` ?

**Comment by usimarit** [comment]
Please check if you use this dataset class
![Screenshot from 2020-12-15 20-33-45](https://user-images.githubusercontent.com/28498441/102221578-e0e60980-3f14-11eb-883e-ce0288069cf1.png)

**Comment by mjurkus** [comment]
Yes, I'm using the script from the `examples/conformer/test_subwords_conformer.py`

**Comment by usimarit** [comment]
@mjurkus That's unusual, I just tested in my local and everything is fine.
Try pulling newest commits and redo:
```bash
pip uninstall TensorFlowASR
python setup.py install
```

**Comment by mjurkus** [comment]
I've installed `TensorFlowASR` via `PyPi`. But now I see that the latest version is `0.4.5`.

**Comment by usimarit** [comment]
> I checked what's happening there ant it seems, that it receives such batch

This batch as you said is the training batch, the batch generated from ASR...TestDataset is `file_paths, signals, labels = batch`
Can you provide the whole error from the command you run to the end?

**Comment by mjurkus** [comment]
Sure. 

```
[Test]:   0%|                                                                                                                                                                                                                                                 | 0/2269 [00:00<?, ?batch/s]Traceback (most recent call last):
  File "conformer/test_subword_conformer.py", line 108, in <module>
    conformer_tester.run(test_dataset)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow_asr/runners/base_runners.py", line 405, in run
    self._test_epoch()
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow_asr/runners/base_runners.py", line 416, in _test_epoch
    decoded = self._test_function(test_iter)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3735, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow_asr/runners/base_runners.py:431 _test_function  *
        return self._test_step(batch)
    /opt/pysetup/.venv/lib/python3.6/site-packages/tensorflow_asr/runners/base_runners.py:443 _test_step  *
        file_paths, signals, labels = batch

    ValueError: too many values to unpack (expected 3
```

**Comment by usimarit** [comment]
Are you sure you get the newest example script? because there's no line 108 in current `test_subword_conformer.py`

**Comment by mjurkus** [comment]
Yes, I'm sure. There is line 108 because I added a couple of lines when I was debugging the issue.

**Comment by mjurkus** [comment]
Maybe I could prepare a sample project that is ready to run?

**Comment by usimarit** [comment]
> Maybe I could prepare a sample project that is ready to run?

Yeah, could you create something like a colab notebook that reproduces this issue? That would be really helpful.

**Comment by mjurkus** [comment]
Tried to reproduce on colab notebook - everything ran perfectly... 🤦🏼 
Now gonna go with fine-toothed comb to find the issue on my side... Sorry for the trouble. Maybe something with dependencies... I don't know. Used same configuration files as in my training machine... So weird...
