### ISSUE TITLE
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'

### ISSUE THREAD

**Issue by Sar-Dar** [TensorSpeech/TensorFlowASR#88]
my environment：
python = 3.7.9
tensorflow = 2.3.0
cuda = 10.1

I installed rnnt loss successfully, but when I trying to run your example for the conformer, following error occur:
`Traceback (most recent call last):
  File "/opt/sardar/TensorFlowASR/examples/conformer/train_conformer.py", line 63, in <module>
    from tensorflow_asr.runners.transducer_runners import TransducerTrainer
  File "/opt/sardar/TensorFlowASR/tensorflow_asr/runners/transducer_runners.py", line 21, in <module>
    from ..losses.rnnt_losses import rnnt_loss
  File "/opt/sardar/TensorFlowASR/tensorflow_asr/losses/rnnt_losses.py", line 16, in <module>
    from warprnnt_tensorflow import rnnt_loss as warp_rnnt_loss
  File "/opt/sardar/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg/warprnnt_tensorflow/__init__.py", line 44, in <module>
    @ops.RegisterShape("WarpRNNT")
AttributeError: module 'tensorflow.python.framework.ops' has no attribute 'RegisterShape'`

can someone give some help? Thanks in advance!

**Comment by usimarit** [comment]
How did you install rnnt loss?

**Comment by Sar-Dar** [comment]
use this conmmand you provide
```
export CUDA_HOME=/usr/local/cuda && ./scripts/install_rnnt_loss.sh
```
And got this output
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.1") 
-- cuda found TRUE
-- Building shared library with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/sardar/TensorFlowASR/externals/warp-transducer/build
(tensorflow2) sardar@ubuntu:~/TensorFlowASR/externals/warp-transducer/build$ make
[  7%] Building NVCC (Device) object CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o
Scanning dependencies of target warprnnt
[ 14%] Linking CXX shared library libwarprnnt.so
[ 14%] Built target warprnnt
[ 21%] Building NVCC (Device) object CMakeFiles/test_time_gpu.dir/tests/test_time_gpu_generated_test_time.cu.o
Scanning dependencies of target test_time_gpu
[ 28%] Building CXX object CMakeFiles/test_time_gpu.dir/tests/random.cpp.o
g++: warning: /usr/bin/c++: linker input file unused because linking not done
[ 35%] Linking CXX executable test_time_gpu
[ 35%] Built target test_time_gpu
[ 42%] Building NVCC (Device) object CMakeFiles/test_gpu.dir/tests/test_gpu_generated_test_gpu.cu.o
Scanning dependencies of target test_gpu
[ 50%] Building CXX object CMakeFiles/test_gpu.dir/tests/random.cpp.o
g++: warning: /usr/bin/c++: linker input file unused because linking not done
[ 57%] Linking CXX executable test_gpu
[ 57%] Built target test_gpu
Scanning dependencies of target test_cpu
[ 64%] Building CXX object CMakeFiles/test_cpu.dir/tests/test_cpu.cpp.o
g++: warning: /usr/bin/c++: linker input file unused because linking not done
[ 71%] Building CXX object CMakeFiles/test_cpu.dir/tests/random.cpp.o
g++: warning: /usr/bin/c++: linker input file unused because linking not done
[ 78%] Linking CXX executable test_cpu
[ 78%] Built target test_cpu
Scanning dependencies of target test_time
[ 85%] Building CXX object CMakeFiles/test_time.dir/tests/test_time.cpp.o
g++: warning: /usr/bin/c++: linker input file unused because linking not done
[ 92%] Building CXX object CMakeFiles/test_time.dir/tests/random.cpp.o
g++: warning: /usr/bin/c++: linker input file unused because linking not done
[100%] Linking CXX executable test_time
[100%] Built target test_time
```
and
```
2020-12-27 18:33:52.454676: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
running install
running bdist_egg
running egg_info
writing warprnnt_tensorflow.egg-info/PKG-INFO
writing dependency_links to warprnnt_tensorflow.egg-info/dependency_links.txt
writing top-level names to warprnnt_tensorflow.egg-info/top_level.txt
reading manifest file 'warprnnt_tensorflow.egg-info/SOURCES.txt'
writing manifest file 'warprnnt_tensorflow.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/warprnnt_tensorflow
copying build/lib.linux-x86_64-3.7/warprnnt_tensorflow/kernels.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/warprnnt_tensorflow
copying build/lib.linux-x86_64-3.7/warprnnt_tensorflow/__init__.py -> build/bdist.linux-x86_64/egg/warprnnt_tensorflow
byte-compiling build/bdist.linux-x86_64/egg/warprnnt_tensorflow/__init__.py to __init__.cpython-37.pyc
creating stub loader for warprnnt_tensorflow/kernels.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/warprnnt_tensorflow/kernels.py to kernels.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying warprnnt_tensorflow.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying warprnnt_tensorflow.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying warprnnt_tensorflow.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying warprnnt_tensorflow.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
warprnnt_tensorflow.__pycache__.__init__.cpython-37: module references __path__
warprnnt_tensorflow.__pycache__.kernels.cpython-37: module references __file__
creating 'dist/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg
creating /opt/sardar/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg
Extracting warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg to /opt/sardar/anaconda3/envs/tensorflow2/lib/python3.7/site-packages
Adding warprnnt-tensorflow 0.1 to easy-install.pth file

Installed /opt/sardar/anaconda3/envs/tensorflow2/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg
Processing dependencies for warprnnt-tensorflow==0.1
Finished processing dependencies for warprnnt-tensorflow==0.1
```

**Comment by usimarit** [comment]
Try reinstalling tensorflow and then rnnt_loss.

**Comment by Sar-Dar** [comment]
> Try reinstalling `tensorflow` and then `rnnt_loss`, then run `pip install .`
same result occurred
I tried in different device,  also got same error

**Comment by usimarit** [comment]
Try removing the directory `./externals/warp-transducer` and return `./scripts/install_rnnt_loss.sh`.
The message says that no `RegisterShape` but I commented out that line in `warp-transducer`.

**Comment by Sar-Dar** [comment]
ok, I commented out that line, it works,  thanks a lot.
